	var habacuque;
	var c  = [];
	var v = [];
	
	function salvaCapitulo(i,v1){
		c[i] = v1;
		v = [];
	}
	
v[1]  =  'O PESO que viu o profeta Habacuque.';
v[2]  =  'Até quando, SENHOR, clamarei eu, e tu não me escutarás? Gritar-te-ei: Violência! e não salvarás?';
v[3]  =  'Por que razão me mostras a iniqüidade, e me fazes ver a opressão? Pois que a destruição e a violência estão diante de mim, havendo também quem suscite a contenda e o litígio.';
v[4]  =  'Por esta causa a lei se afrouxa, e a justiça nunca se manifesta; porque o ímpio cerca o justo, e a justiça se manifesta distorcida.';
v[5]  =  'Vede entre os gentios e olhai, e maravilhai-vos, e admirai-vos; porque realizarei em vossos dias uma obra que vós não crereis, quando for contada.';
v[6]  =  'Porque eis que suscito os caldeus, nação amarga e impetuosa, que marcha sobre a largura da terra, para apoderar-se de moradas que não são suas.';
v[7]  =  'Horrível e terrível é; dela mesma sairá o seu juízo e a sua dignidade.';
v[8]  =  'E os seus cavalos são mais ligeiros do que os leopardos, e mais espertos do que os lobos à tarde; os seus cavaleiros espalham-se por toda parte; os seus cavaleiros virão de longe; voarão como águias que se apressam a devorar.';
v[9]  =  'Eles todos virão para fazer violência; os seus rostos buscarão o vento oriental, e reunirão os cativos como areia.';
v[10]  =  'E escarnecerão dos reis, e dos príncipes farão zombaria; eles se rirão de todas as fortalezas, porque amontoarão terra, e as tomarão.';
v[11]  =  'Então muda a sua mente, e seguirá, e se fará culpado, atribuindo este seu poder ao seu deus.';
v[12]  =  'Não és tu desde a eternidade, ó SENHOR meu Deus, meu Santo? Nós não morreremos. Ó SENHOR, para juízo o puseste, e tu, ó Rocha, o fundaste para castigar.';
v[13]  =  'Tu és tão puro de olhos, que não podes ver o mal, e a opressão não podes contemplar. Por que olhas para os que procedem aleivosamente, e te calas quando o ímpio devora aquele que é mais justo do que ele?';
v[14]  =  'E por que farias os homens como os peixes do mar, como os répteis, que não têm quem os governe?';
v[15]  =  'Ele a todos levantará com o anzol, apanhá-los-á com a sua rede, e os ajuntará na sua rede varredoura; por isso ele se alegrará e se regozijará.';
v[16]  =  'Por isso sacrificará à sua rede, e queimará incenso à sua varredoura; porque com elas engordou a sua porção, e engrossou a sua comida.';
v[17]  =  'Porventura por isso esvaziará a sua rede e não terá piedade de matar as nações continuamente?';
salvaCapitulo(1, v);
v[1]  =  'SOBRE a minha guarda estarei, e sobre a fortaleza me apresentarei e vigiarei, para ver o que falará a mim, e o que eu responderei quando eu for argüido.';
v[2]  =  'Então o SENHOR me respondeu, e disse: Escreve a visão e torna bem legível sobre tábuas, para que a possa ler quem passa correndo.';
v[3]  =  'Porque a visão é ainda para o tempo determinado, mas se apressa para o fim, e não enganará; se tardar, espera-o, porque certamente virá, não tardará.';
v[4]  =  'Eis que a sua alma está orgulhosa, não é reta nele; mas o justo pela sua fé viverá.';
v[5]  =  'Tanto mais que, por ser dado ao vinho é desleal; homem soberbo que não permanecerá; que alarga como o inferno a sua alma; e é como a morte que não se farta, e ajunta a si todas as nações, e congrega a si todos os povos.';
v[6]  =  'Não levantarão, pois, todos estes contra ele uma parábola e um provérbio sarcástico contra ele? E se dirá: Ai daquele que multiplica o que não é seu! (até quando?) e daquele que carrega sobre si dívidas!';
v[7]  =  'Porventura não se levantarão de repente os teus extorquiadores, e não despertarão os que te farão tremer, e não lhes servirás tu de despojo?';
v[8]  =  'Porquanto despojaste a muitas nações, todos os demais povos te despojarão a ti, por causa do sangue dos homens, e da violência feita à terra, à cidade, e a todos os que nela habitam.';
v[9]  =  'Ai daquele que, para a sua casa, ajunta cobiçosamente bens mal adquiridos, para pôr o seu ninho no alto, a fim de se livrar do poder do mal!';
v[10]  =  'Vergonha maquinaste para a tua casa; destruindo tu a muitos povos, pecaste contra a tua alma.';
v[11]  =  'Porque a pedra clamará da parede, e a trave lhe responderá do madeiramento.';
v[12]  =  'Ai daquele que edifica a cidade com sangue, e que funda a cidade com iniqüidade!';
v[13]  =  'Porventura não vem do SENHOR dos Exércitos que os povos trabalhem pelo fogo e os homens se cansem em vão?';
v[14]  =  'Porque a terra se encherá do conhecimento da glória do SENHOR, como as águas cobrem o mar.';
v[15]  =  'Ai daquele que dá de beber ao seu companheiro! Ai de ti, que adiciona à bebida o teu furor, e o embebedas para ver a sua nudez!';
v[16]  =  'Serás farto de ignomínia em lugar de honra; bebe tu também, e sê como um incircunciso; o cálice da mão direita do SENHOR voltará a ti, e ignomínia cairá sobre a tua glória.';
v[17]  =  'Porque a violência cometida contra o Líbano te cobrirá, e a destruição das feras te amedrontará, por causa do sangue dos homens, e da violência feita à terra, à cidade, e a todos os que nela habitam.';
v[18]  =  'Que aproveita a imagem de escultura, depois que a esculpiu o seu artífice? Ela é máscara e ensina mentira, para que quem a formou confie na sua obra, fazendo ídolos mudos?';
v[19]  =  'Ai daquele que diz ao pau: Acorda! e à pedra muda: Desperta! Pode isso ensinar? Eis que está coberta de ouro e de prata, mas dentro dela não há espírito algum.';
v[20]  =  'Mas o SENHOR está no seu santo templo; cale-se diante dele toda a terra.';
salvaCapitulo(2, v);
v[1]  =  'ORAÇÃO do profeta Habacuque sobre Sigionote.';
v[2]  =  'Ouvi, SENHOR, a tua palavra, e temi; aviva, ó SENHOR, a tua obra no meio dos anos, no meio dos anos faze-a conhecida; na tua ira lembra-te da misericórdia.';
v[3]  =  'Deus veio de Temã, e do monte de Parã o Santo (Selá). A sua glória cobriu os céus, e a terra encheu-se do seu louvor.';
v[4]  =  'E o resplendor se fez como a luz, raios brilhantes saíam da sua mão, e ali estava o esconderijo da sua força.';
v[5]  =  'Adiante dele ia a peste, e brasas ardentes saíam dos seus passos.';
v[6]  =  'Parou, e mediu a terra; olhou, e separou as nações; e os montes perpétuos foram esmiuçados; ou outeiros eternos se abateram, porque os caminhos eternos lhe pertencem.';
v[7]  =  'Vi as tendas de Cusã em aflição; tremiam as cortinas da terra de Midiã.';
v[8]  =  'Acaso é contra os rios, SENHOR, que estás irado? É contra os ribeiros a tua ira, ou contra o mar o teu furor, visto que andas montado sobre os teus cavalos, e nos teus carros de salvação?';
v[9]  =  'Descoberto se movimentou o teu arco; os juramentos feitos às tribos foram uma palavra segura. (Selá.) Tu fendeste a terra com rios.';
v[10]  =  'Os montes te viram, e tremeram; a inundação das águas passou; o abismo deu a sua voz, levantou ao alto as suas mãos.';
v[11]  =  'O sol e a lua pararam nas suas moradas; andaram à luz das tuas flechas, ao resplendor do relâmpago da tua lança.';
v[12]  =  'Com indignação marchaste pela terra, com ira trilhaste os gentios.';
v[13]  =  'Tu saíste para salvação do teu povo, para salvação do teu ungido; tu feriste a cabeça da casa do ímpio, descobrindo o alicerce até ao pescoço. (Selá.)';
v[14]  =  'Tu traspassaste com as suas próprias lanças a cabeça das suas vilas; eles me acometeram tempestuosos para me espalharem; alegravam-se, como se estivessem para devorar o pobre em segredo.';
v[15]  =  'Tu com os teus cavalos marchaste pelo mar, pela massa de grandes águas.';
v[16]  =  'Ouvindo-o eu, o meu ventre se comoveu, à sua voz tremeram os meus lábios; entrou a podridão nos meus ossos, e estremeci dentro de mim; no dia da angústia descansarei, quando subir contra o povo que invadirá com suas tropas.';
v[17]  =  'Porque ainda que a figueira não floresça, nem haja fruto na vide; ainda que decepcione o produto da oliveira, e os campos não produzam mantimento; ainda que as ovelhas da malhada sejam arrebatadas, e nos currais não haja gado;';
v[18]  =  'Todavia eu me alegrarei no SENHOR; exultarei no Deus da minha salvação.';
v[19]  =  'O SENHOR Deus é a minha força, e fará os meus pés como os das cervas, e me fará andar sobre as minhas alturas. (Para o cantor-mor sobre os meus instrumentos de corda).';
salvaCapitulo(3, v);
		
	habacuque = c;