	var iPedro;
	var c  = [];
	var v = [];
	
	function salvaCapitulo(i,v1){
		c[i] = v1;
		v = [];
	}
	
	

v[1]  =  'PEDRO, apóstolo de Jesus Cristo, aos estrangeiros dispersos no Ponto, Galácia, Capadócia, Ásia e Bitínia;';
v[2]  =  'Eleitos segundo a presciência de Deus Pai, em santificação do Espírito, para a obediência e aspersão do sangue de Jesus Cristo: Graça e paz vos sejam multiplicadas.';
v[3]  =  'Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo que, segundo a sua grande misericórdia, nos gerou de novo para uma viva esperança, pela ressurreição de Jesus Cristo dentre os mortos,';
v[4]  =  'Para uma herança incorruptível, incontaminável, e que não se pode murchar, guardada nos céus para vós,';
v[5]  =  'Que mediante a fé estais guardados na virtude de Deus para a salvação, já prestes para se revelar no último tempo,';
v[6]  =  'Em que vós grandemente vos alegrais, ainda que agora importa, sendo necessário, que estejais por um pouco contristados com várias tentações,';
v[7]  =  'Para que a prova da vossa fé, muito mais preciosa do que o ouro que perece e é provado pelo fogo, se ache em louvor, e honra, e glória, na revelação de Jesus Cristo;';
v[8]  =  'Ao qual, não o havendo visto, amais; no qual, não o vendo agora, mas crendo, vos alegrais com gozo inefável e glorioso;';
v[9]  =  'Alcançando o fim da vossa fé, a salvação das vossas almas.';
v[10]  =  'Da qual salvação inquiriram e trataram diligentemente os profetas que profetizaram da graça que vos foi dada,';
v[11]  =  'Indagando que tempo ou que ocasião de tempo o Espírito de Cristo, que estava neles, indicava, anteriormente testificando os sofrimentos que a Cristo haviam de vir, e a glória que se lhes havia de seguir.';
v[12]  =  'Aos quais foi revelado que, não para si mesmos, mas para nós, eles ministravam estas coisas que agora vos foram anunciadas por aqueles que, pelo Espírito Santo enviado do céu, vos pregaram o evangelho; para as quais coisas os anjos desejam bem atentar.';
v[13]  =  'Portanto, cingindo os lombos do vosso entendimento, sede sóbrios, e esperai inteiramente na graça que se vos ofereceu na revelação de Jesus Cristo;';
v[14]  =  'Como filhos obedientes, não vos conformando com as concupiscências que antes havia em vossa ignorância;';
v[15]  =  'Mas, como é santo aquele que vos chamou, sede vós também santos em toda a vossa maneira de viver;';
v[16]  =  'Porquanto está escrito: Sede santos, porque eu sou santo.';
v[17]  =  'E, se invocais por Pai aquele que, sem acepção de pessoas, julga segundo a obra de cada um, andai em temor, durante o tempo da vossa peregrinação,';
v[18]  =  'Sabendo que não foi com coisas corruptíveis, como prata ou ouro, que fostes resgatados da vossa vã maneira de viver que por tradição recebestes dos vossos pais,';
v[19]  =  'Mas com o precioso sangue de Cristo, como de um cordeiro imaculado e incontaminado,';
v[20]  =  'O qual, na verdade, em outro tempo foi conhecido, ainda antes da fundação do mundo, mas manifestado nestes últimos tempos por amor de vós;';
v[21]  =  'E por ele credes em Deus, que o ressuscitou dentre os mortos, e lhe deu glória, para que a vossa fé e esperança estivessem em Deus;';
v[22]  =  'Purificando as vossas almas pelo Espírito na obediência à verdade, para o amor fraternal, não fingido; amai-vos ardentemente uns aos outros com um coração puro;';
v[23]  =  'Sendo de novo gerados, não de semente corruptível, mas da incorruptível, pela palavra de Deus, viva, e que permanece para sempre.';
v[24]  =  'Porque Toda a carne é como a erva, E toda a glória do homem como a flor da erva. Secou-se a erva, e caiu a sua flor;';
v[25]  =  'Mas a palavra do SENHOR permanece para sempre. E esta é a palavra que entre vós foi evangelizada.';
salvaCapitulo(1, v);
v[1]  =  'DEIXANDO, pois, toda a malícia, e todo o engano, e fingimentos, e invejas, e todas as murmurações,';
v[2]  =  'Desejai afetuosamente, como meninos novamente nascidos, o leite racional, não falsificado, para que por ele vades crescendo;';
v[3]  =  'Se é que já provastes que o SENHOR é benigno;';
v[4]  =  'E, chegando-vos para ele, pedra viva, reprovada, na verdade, pelos homens, mas para com Deus eleita e preciosa,';
v[5]  =  'Vós também, como pedras vivas, sois edificados casa espiritual e sacerdócio santo, para oferecer sacrifícios espirituais agradáveis a Deus por Jesus Cristo.';
v[6]  =  'Por isso também na Escritura se contém: Eis que ponho em Sião a pedra principal da esquina, eleita e preciosa; E quem nela crer não será confundido.';
v[7]  =  'E assim para vós, os que credes, é preciosa, mas, para os rebeldes, A pedra que os edificadores reprovaram, Essa foi a principal da esquina,';
v[8]  =  'E uma pedra de tropeço e rocha de escândalo, para aqueles que tropeçam na palavra, sendo desobedientes; para o que também foram destinados.';
v[9]  =  'Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo adquirido, para que anuncieis as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz;';
v[10]  =  'Vós, que em outro tempo não éreis povo, mas agora sois povo de Deus; que não tínheis alcançado misericórdia, mas agora alcançastes misericórdia.';
v[11]  =  'Amados, peço-vos, como a peregrinos e forasteiros, que vos abstenhais das concupiscências carnais que combatem contra a alma;';
v[12]  =  'Tendo o vosso viver honesto entre os gentios; para que, naquilo em que falam mal de vós, como de malfeitores, glorifiquem a Deus no dia da visitação, pelas boas obras que em vós observem.';
v[13]  =  'Sujeitai-vos, pois, a toda a ordenação humana por amor do Senhor; quer ao rei, como superior;';
v[14]  =  'Quer aos governadores, como por ele enviados para castigo dos malfeitores, e para louvor dos que fazem o bem.';
v[15]  =  'Porque assim é a vontade de Deus, que, fazendo bem, tapeis a boca à ignorância dos homens insensatos;';
v[16]  =  'Como livres, e não tendo a liberdade por cobertura da malícia, mas como servos de Deus.';
v[17]  =  'Honrai a todos. Amai a fraternidade. Temei a Deus. Honrai ao rei.';
v[18]  =  'Vós, servos, sujeitai-vos com todo o temor aos SENHORes, não somente aos bons e humanos, mas também aos maus.';
v[19]  =  'Porque é coisa agradável, que alguém, por causa da consciência para com Deus, sofra agravos, padecendo injustamente.';
v[20]  =  'Porque, que glória será essa, se, pecando, sois esbofeteados e sofreis? Mas se, fazendo o bem, sois afligidos e o sofreis, isso é agradável a Deus.';
v[21]  =  'Porque para isto sois chamados; pois também Cristo padeceu por nós, deixando-nos o exemplo, para que sigais as suas pisadas.';
v[22]  =  'O qual não cometeu pecado, nem na sua boca se achou engano.';
v[23]  =  'O qual, quando o injuriavam, não injuriava, e quando padecia não ameaçava, mas entregava-se àquele que julga justamente;';
v[24]  =  'Levando ele mesmo em seu corpo os nossos pecados sobre o madeiro, para que, mortos para os pecados, pudéssemos viver para a justiça; e pelas suas feridas fostes sarados.';
v[25]  =  'Porque éreis como ovelhas desgarradas; mas agora tendes voltado ao Pastor e Bispo das vossas almas.';
salvaCapitulo(2, v);
v[1]  =  'SEMELHANTEMENTE, vós, mulheres, sede sujeitas aos vossos próprios maridos; para que também, se alguns não obedecem à palavra, pelo porte de suas mulheres sejam ganhos sem palavra;';
v[2]  =  'Considerando a vossa vida casta, em temor.';
v[3]  =  'O enfeite delas não seja o exterior, no frisado dos cabelos, no uso de jóias de ouro, na compostura dos vestidos;';
v[4]  =  'Mas o homem encoberto no coração; no incorruptível traje de um espírito manso e quieto, que é precioso diante de Deus.';
v[5]  =  'Porque assim se adornavam também antigamente as santas mulheres que esperavam em Deus, e estavam sujeitas aos seus próprios maridos;';
v[6]  =  'Como Sara obedecia a Abraão, chamando-lhe senhor; da qual vós sois filhas, fazendo o bem, e não temendo nenhum espanto.';
v[7]  =  'Igualmente vós, maridos, coabitai com elas com entendimento, dando honra à mulher, como vaso mais fraco; como sendo vós os seus co-herdeiros da graça da vida; para que não sejam impedidas as vossas orações.';
v[8]  =  'E, finalmente, sede todos de um mesmo sentimento, compassivos, amando os irmãos, entranhavelmente misericordiosos e afáveis.';
v[9]  =  'Não tornando mal por mal, ou injúria por injúria; antes, pelo contrário, bendizendo; sabendo que para isto fostes chamados, para que por herança alcanceis a bênção.';
v[10]  =  'Porque Quem quer amar a vida, E ver os dias bons, Refreie a sua língua do mal, E os seus lábios não falem engano.';
v[11]  =  'Aparte-se do mal, e faça o bem; Busque a paz, e siga-a.';
v[12]  =  'Porque os olhos do Senhor estão sobre os justos, E os seus ouvidos atentos às suas orações; Mas o rosto do Senhor é contra os que fazem o mal.';
v[13]  =  'E qual é aquele que vos fará mal, se fordes zelosos do bem?';
v[14]  =  'Mas também, se padecerdes por amor da justiça, sois bem-aventurados. E não temais com medo deles, nem vos turbeis;';
v[15]  =  'Antes, santificai ao SENHOR Deus em vossos corações; e estai sempre preparados para responder com mansidão e temor a qualquer que vos pedir a razão da esperança que há em vós,';
v[16]  =  'Tendo uma boa consciência, para que, naquilo em que falam mal de vós, como de malfeitores, fiquem confundidos os que blasfemam do vosso bom porte em Cristo.';
v[17]  =  'Porque melhor é que padeçais fazendo bem (se a vontade de Deus assim o quer), do que fazendo mal.';
v[18]  =  'Porque também Cristo padeceu uma vez pelos pecados, o justo pelos injustos, para levar-nos a Deus; mortificado, na verdade, na carne, mas vivificado pelo Espírito;';
v[19]  =  'No qual também foi, e pregou aos espíritos em prisão;';
v[20]  =  'Os quais noutro tempo foram rebeldes, quando a longanimidade de Deus esperava nos dias de Noé, enquanto se preparava a arca; na qual poucas (isto é, oito) almas se salvaram pela água;';
v[21]  =  'Que também, como uma verdadeira figura, agora vos salva, o batismo, não do despojamento da imundícia da carne, mas da indagação de uma boa consciência para com Deus, pela ressurreição de Jesus Cristo;';
v[22]  =  'O qual está à destra de Deus, tendo subido ao céu, havendo-se-lhe sujeitado os anjos, e as autoridades, e as potências.';
salvaCapitulo(3, v);
v[1]  =  'ORA, pois, já que Cristo padeceu por nós na carne, armai-vos também vós com este pensamento, que aquele que padeceu na carne já cessou do pecado;';
v[2]  =  'Para que, no tempo que vos resta na carne, não vivais mais segundo as concupiscências dos homens, mas segundo a vontade de Deus.';
v[3]  =  'Porque é bastante que no tempo passado da vida fizéssemos a vontade dos gentios, andando em dissoluções, concupiscências, borrachices, glutonarias, bebedices e abomináveis idolatrias;';
v[4]  =  'E acham estranho não correrdes com eles no mesmo desenfreamento de dissolução, blasfemando de vós.';
v[5]  =  'Os quais hão de dar conta ao que está preparado para julgar os vivos e os mortos.';
v[6]  =  'Porque por isto foi pregado o evangelho também aos mortos, para que, na verdade, fossem julgados segundo os homens na carne, mas vivessem segundo Deus em espírito;';
v[7]  =  'E já está próximo o fim de todas as coisas; portanto sede sóbrios e vigiai em oração.';
v[8]  =  'Mas, sobretudo, tende ardente amor uns para com os outros; porque o amor cobrirá a multidão de pecados.';
v[9]  =  'Sendo hospitaleiros uns para com os outros, sem murmurações,';
v[10]  =  'Cada um administre aos outros o dom como o recebeu, como bons despenseiros da multiforme graça de Deus.';
v[11]  =  'Se alguém falar, fale segundo as palavras de Deus; se alguém administrar, administre segundo o poder que Deus dá; para que em tudo Deus seja glorificado por Jesus Cristo, a quem pertence a glória e poder para todo o sempre. Amém.';
v[12]  =  'Amados, não estranheis a ardente prova que vem sobre vós para vos tentar, como se coisa estranha vos acontecesse;';
v[13]  =  'Mas alegrai-vos no fato de serdes participantes das aflições de Cristo, para que também na revelação da sua glória vos regozijeis e alegreis.';
v[14]  =  'Se pelo nome de Cristo sois vituperados, bem-aventurados sois, porque sobre vós repousa o Espírito da glória e de Deus; quanto a eles, é ele, sim, blasfemado, mas quanto a vós, é glorificado.';
v[15]  =  'Que nenhum de vós padeça como homicida, ou ladrão, ou malfeitor, ou como o que se entremete em negócios alheios;';
v[16]  =  'Mas, se padece como cristão, não se envergonhe, antes glorifique a Deus nesta parte.';
v[17]  =  'Porque já é tempo que comece o julgamento pela casa de Deus; e, se primeiro começa por nós, qual será o fim daqueles que são desobedientes ao evangelho de Deus?';
v[18]  =  'E, se o justo apenas se salva, onde aparecerá o ímpio e o pecador?';
v[19]  =  'Portanto também os que padecem segundo a vontade de Deus encomendem-lhe as suas almas, como ao fiel Criador, fazendo o bem.';
salvaCapitulo(4, v);
v[1]  =  'AOS presbíteros, que estão entre vós, admoesto eu, que sou também presbítero com eles, e testemunha das aflições de Cristo, e participante da glória que se há de revelar:';
v[2]  =  'Apascentai o rebanho de Deus, que está entre vós, tendo cuidado dele, não por força, mas voluntariamente; nem por torpe ganância, mas de ânimo pronto;';
v[3]  =  'Nem como tendo domínio sobre a herança de Deus, mas servindo de exemplo ao rebanho.';
v[4]  =  'E, quando aparecer o Sumo Pastor, alcançareis a incorruptível coroa da glória.';
v[5]  =  'Semelhantemente vós jovens, sede sujeitos aos anciãos; e sede todos sujeitos uns aos outros, e revesti-vos de humildade, porque Deus resiste aos soberbos, mas dá graça aos humildes.';
v[6]  =  'Humilhai-vos, pois, debaixo da potente mão de Deus, para que a seu tempo vos exalte;';
v[7]  =  'Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.';
v[8]  =  'Sede sóbrios; vigiai; porque o diabo, vosso adversário, anda em derredor, bramando como leão, buscando a quem possa tragar;';
v[9]  =  'Ao qual resisti firmes na fé, sabendo que as mesmas aflições se cumprem entre os vossos irmãos no mundo.';
v[10]  =  'E o Deus de toda a graça, que em Cristo Jesus vos chamou à sua eterna glória, depois de haverdes padecido um pouco, ele mesmo vos aperfeiçoará, confirmará, fortificará e fortalecerá.';
v[11]  =  'A ele seja a glória e o poderio para todo o sempre. Amém.';
v[12]  =  'Por Silvano, vosso fiel irmão, como cuido, escrevi abreviadamente, exortando e testificando que esta é a verdadeira graça de Deus, na qual estais firmes.';
v[13]  =  'A vossa co-eleita em Babilônia vos saúda, e meu filho Marcos.';
v[14]  =  'Saudai-vos uns aos outros com ósculo de amor. Paz seja com todos vós que estais em Cristo Jesus. Amém.';
salvaCapitulo(5, v);

	
	
	iPedro = c;
