	var iTessalonicenses;
	var c  = [];
	var v = [];
	
	function salvaCapitulo(i,v1){
		c[i] = v1;
		v = [];
	}
	
	

v[1]  =  'PAULO, e Silvano, e Timóteo, à igreja dos tessalonicenses em Deus, o Pai, e no Senhor Jesus Cristo: Graça e paz tenhais de Deus nosso Pai e do Senhor Jesus Cristo.';
v[2]  =  'Sempre damos graças a Deus por vós todos, fazendo menção de vós em nossas orações,';
v[3]  =  'Lembrando-nos sem cessar da obra da vossa fé, do trabalho do amor, e da paciência da esperança em nosso Senhor Jesus Cristo, diante de nosso Deus e Pai,';
v[4]  =  'Sabendo, amados irmãos, que a vossa eleição é de Deus;';
v[5]  =  'Porque o nosso evangelho não foi a vós somente em palavras, mas também em poder, e no Espírito Santo, e em muita certeza, como bem sabeis quais fomos entre vós, por amor de vós.';
v[6]  =  'E vós fostes feitos nossos imitadores, e do Senhor, recebendo a palavra em muita tribulação, com gozo do Espírito Santo.';
v[7]  =  'De maneira que fostes exemplo para todos os fiéis na Macedônia e Acaia.';
v[8]  =  'Porque por vós soou a palavra do Senhor, não somente na Macedônia e Acaia, mas também em todos os lugares a vossa fé para com Deus se espalhou, de tal maneira que já dela não temos necessidade de falar coisa alguma;';
v[9]  =  'Porque eles mesmos anunciam de nós qual a entrada que tivemos para convosco, e como dos ídolos vos convertestes a Deus, para servir o Deus vivo e verdadeiro,';
v[10]  =  'E esperar dos céus a seu Filho, a quem ressuscitou dentre os mortos, a saber, Jesus, que nos livra da ira futura.';
salvaCapitulo(1, v);
v[1]  =  'PORQUE vós mesmos, irmãos, bem sabeis que a nossa entrada para convosco não foi vã;';
v[2]  =  'Mas, mesmo depois de termos antes padecido, e sido agravados em Filipos, como sabeis, tornamo-nos ousados em nosso Deus, para vos falar o evangelho de Deus com grande combate.';
v[3]  =  'Porque a nossa exortação não foi com engano, nem com imundícia, nem com fraudulência;';
v[4]  =  'Mas, como fomos aprovados de Deus para que o evangelho nos fosse confiado, assim falamos, não como para agradar aos homens, mas a Deus, que prova os nossos corações.';
v[5]  =  'Porque, como bem sabeis, nunca usamos de palavras lisonjeiras, nem houve um pretexto de avareza; Deus é testemunha;';
v[6]  =  'E não buscamos glória dos homens, nem de vós, nem de outros, ainda que podíamos, como apóstolos de Cristo, ser-vos pesados;';
v[7]  =  'Antes fomos brandos entre vós, como a ama que cria seus filhos.';
v[8]  =  'Assim nós, sendo-vos tão afeiçoados, de boa vontade quiséramos comunicar-vos, não somente o evangelho de Deus, mas ainda as nossas próprias almas; porquanto nos éreis muito queridos.';
v[9]  =  'Porque bem vos lembrais, irmãos, do nosso trabalho e fadiga; pois, trabalhando noite e dia, para não sermos pesados a nenhum de vós, vos pregamos o evangelho de Deus.';
v[10]  =  'Vós e Deus sois testemunhas de quão santa, e justa, e irrepreensivelmente nos houvemos para convosco, os que crestes.';
v[11]  =  'Assim como bem sabeis de que modo vos exortávamos e consolávamos, a cada um de vós, como o pai a seus filhos;';
v[12]  =  'Para que vos conduzísseis dignamente para com Deus, que vos chama para o seu reino e glória.';
v[13]  =  'Por isso também damos, sem cessar, graças a Deus, pois, havendo recebido de nós a palavra da pregação de Deus, a recebestes, não como palavra de homens, mas (segundo é, na verdade), como palavra de Deus, a qual também opera em vós, os que crestes.';
v[14]  =  'Porque vós, irmãos, haveis sido feitos imitadores das igrejas de Deus que na Judéia estão em Jesus Cristo; porquanto também padecestes de vossos próprios concidadãos o mesmo que os judeus lhes fizeram a eles,';
v[15]  =  'Os quais também mataram o SENHOR Jesus e os seus próprios profetas, e nos têm perseguido; e não agradam a Deus, e são contrários a todos os homens,';
v[16]  =  'E nos impedem de pregar aos gentios as palavras da salvação, a fim de encherem sempre a medida de seus pecados; mas a ira de Deus caiu sobre eles até ao fim.';
v[17]  =  'Nós, porém, irmãos, sendo privados de vós por um momento de tempo, de vista, mas não do coração, tanto mais procuramos com grande desejo ver o vosso rosto;';
v[18]  =  'Por isso bem quisemos uma e outra vez ir ter convosco, pelo menos eu, Paulo, mas Satanás no-lo impediu.';
v[19]  =  'Porque, qual é a nossa esperança, ou gozo, ou coroa de glória? Porventura não o sois vós também diante de nosso Senhor Jesus Cristo em sua vinda?';
v[20]  =  'Na verdade vós sois a nossa glória e gozo.';
salvaCapitulo(2, v);
v[1]  =  'POR isso, não podendo esperar mais, achamos por bem ficar sozinhos em Atenas;';
v[2]  =  'E enviamos Timóteo, nosso irmão, e ministro de Deus, e nosso cooperador no evangelho de Cristo, para vos confortar e vos exortar acerca da vossa fé;';
v[3]  =  'Para que ninguém se comova por estas tribulações; porque vós mesmos sabeis que para isto fomos ordenados,';
v[4]  =  'Pois, estando ainda convosco, vos predizíamos que havíamos de ser afligidos, como sucedeu, e vós o sabeis.';
v[5]  =  'Portanto, não podendo eu também esperar mais, mandei-o saber da vossa fé, temendo que o tentador vos tentasse, e o nosso trabalho viesse a ser inútil.';
v[6]  =  'Vindo, porém, agora Timóteo de vós para nós, e trazendo-nos boas novas da vossa fé e amor, e de como sempre tendes boa lembrança de nós, desejando muito ver-nos, como nós também a vós;';
v[7]  =  'Por esta razão, irmãos, ficamos consolados acerca de vós, em toda a nossa aflição e necessidade, pela vossa fé,';
v[8]  =  'Porque agora vivemos, se estais firmes no Senhor.';
v[9]  =  'Porque, que ação de graças poderemos dar a Deus por vós, por todo o gozo com que nos regozijamos por vossa causa diante do nosso Deus,';
v[10]  =  'Orando abundantemente dia e noite, para que possamos ver o vosso rosto, e supramos o que falta à vossa fé?';
v[11]  =  'Ora, o mesmo nosso Deus e Pai, e nosso Senhor Jesus Cristo, encaminhe a nossa viagem para vós.';
v[12]  =  'E o Senhor vos aumente, e faça crescer em amor uns para com os outros, e para com todos, como também o fazemos para convosco;';
v[13]  =  'Para confirmar os vossos corações, para que sejais irrepreensíveis em santidade diante de nosso Deus e Pai, na vinda de nosso SENHOR Jesus Cristo com todos os seus santos.';
salvaCapitulo(3, v);
v[1]  =  'FINALMENTE, irmãos, vos rogamos e exortamos no Senhor Jesus, que assim como recebestes de nós, de que maneira convém andar e agradar a Deus, assim andai, para que possais progredir cada vez mais.';
v[2]  =  'Porque vós bem sabeis que mandamentos vos temos dado pelo Senhor Jesus.';
v[3]  =  'Porque esta é a vontade de Deus, a vossa santificação; que vos abstenhais da prostituição;';
v[4]  =  'Que cada um de vós saiba possuir o seu vaso em santificação e honra;';
v[5]  =  'Não na paixão da concupiscência, como os gentios, que não conhecem a Deus.';
v[6]  =  'Ninguém oprima ou engane a seu irmão em negócio algum, porque o SENHOR é vingador de todas estas coisas, como também antes vo-lo dissemos e testificamos.';
v[7]  =  'Porque não nos chamou Deus para a imundícia, mas para a santificação.';
v[8]  =  'Portanto, quem despreza isto não despreza ao homem, mas sim a Deus, que nos deu também o seu Espírito Santo.';
v[9]  =  'Quanto, porém, ao amor fraternal, não necessitais de que vos escreva, visto que vós mesmos estais instruídos por Deus que vos ameis uns aos outros;';
v[10]  =  'Porque também já assim o fazeis para com todos os irmãos que estão por toda a Macedônia. Exortamo-vos, porém, a que ainda nisto aumenteis cada vez mais.';
v[11]  =  'E procureis viver quietos, e tratar dos vossos próprios negócios, e trabalhar com vossas próprias mãos, como já vo-lo temos mandado;';
v[12]  =  'Para que andeis honestamente para com os que estão de fora, e não necessiteis de coisa alguma.';
v[13]  =  'Não quero, porém, irmãos, que sejais ignorantes acerca dos que já dormem, para que não vos entristeçais, como os demais, que não têm esperança.';
v[14]  =  'Porque, se cremos que Jesus morreu e ressuscitou, assim também aos que em Jesus dormem, Deus os tornará a trazer com ele.';
v[15]  =  'Dizemo-vos, pois, isto, pela palavra do Senhor: que nós, os que ficarmos vivos para a vinda do Senhor, não precederemos os que dormem.';
v[16]  =  'Porque o mesmo Senhor descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus; e os que morreram em Cristo ressuscitarão primeiro.';
v[17]  =  'Depois nós, os que ficarmos vivos, seremos arrebatados juntamente com eles nas nuvens, a encontrar o Senhor nos ares, e assim estaremos sempre com o Senhor.';
v[18]  =  'Portanto, consolai-vos uns aos outros com estas palavras.';
salvaCapitulo(4, v);
v[1]  =  'MAS, irmãos, acerca dos tempos e das estações, não necessitais de que se vos escreva;';
v[2]  =  'Porque vós mesmos sabeis muito bem que o dia do Senhor virá como o ladrão de noite;';
v[3]  =  'Pois que, quando disserem: Há paz e segurança, então lhes sobrevirá repentina destruição, como as dores de parto àquela que está grávida, e de modo nenhum escaparão.';
v[4]  =  'Mas vós, irmãos, já não estais em trevas, para que aquele dia vos surpreenda como um ladrão;';
v[5]  =  'Porque todos vós sois filhos da luz e filhos do dia; nós não somos da noite nem das trevas.';
v[6]  =  'Não durmamos, pois, como os demais, mas vigiemos, e sejamos sóbrios;';
v[7]  =  'Porque os que dormem, dormem de noite, e os que se embebedam, embebedam-se de noite.';
v[8]  =  'Mas nós, que somos do dia, sejamos sóbrios, vestindo-nos da couraça da fé e do amor, e tendo por capacete a esperança da salvação;';
v[9]  =  'Porque Deus não nos destinou para a ira, mas para a aquisição da salvação, por nosso Senhor Jesus Cristo,';
v[10]  =  'Que morreu por nós, para que, quer vigiemos, quer durmamos, vivamos juntamente com ele.';
v[11]  =  'Por isso exortai-vos uns aos outros, e edificai-vos uns aos outros, como também o fazeis.';
v[12]  =  'E rogamo-vos, irmãos, que reconheçais os que trabalham entre vós e que presidem sobre vós no Senhor, e vos admoestam;';
v[13]  =  'E que os tenhais em grande estima e amor, por causa da sua obra. Tende paz entre vós.';
v[14]  =  'Rogamo-vos, também, irmãos, que admoesteis os desordeiros, consoleis os de pouco ânimo, sustenteis os fracos, e sejais pacientes para com todos.';
v[15]  =  'Vede que ninguém dê a outrem mal por mal, mas segui sempre o bem, tanto uns para com os outros, como para com todos.';
v[16]  =  'Regozijai-vos sempre.';
v[17]  =  'Orai sem cessar.';
v[18]  =  'Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco.';
v[19]  =  'Não extingais o Espírito.';
v[20]  =  'Não desprezeis as profecias.';
v[21]  =  'Examinai tudo. Retende o bem.';
v[22]  =  'Abstende-vos de toda a aparência do mal.';
v[23]  =  'E o mesmo Deus de paz vos santifique em tudo; e todo o vosso espírito, e alma, e corpo, sejam plenamente conservados irrepreensíveis para a vinda de nosso SENHOR Jesus Cristo.';
v[24]  =  'Fiel é o que vos chama, o qual também o fará.';
v[25]  =  'Irmãos, orai por nós.';
v[26]  =  'Saudai a todos os irmãos com ósculo santo.';
v[27]  =  'Pelo Senhor vos conjuro que esta epístola seja lida a todos os santos irmãos.';
v[28]  =  'A graça de nosso Senhor Jesus Cristo seja convosco. Amém.';
salvaCapitulo(5, v);

	
	
	iTessalonicenses = c;
