	var iiTessalonicenses;
	var c  = [];
	var v = [];
	
	function salvaCapitulo(i,v1){
		c[i] = v1;
		v = [];
	}

v[1]  =  'PAULO, e Silvano, e Timóteo, à igreja dos tessalonicenses, em Deus nosso Pai, e no Senhor Jesus Cristo:';
v[2]  =  'Graça e paz a vós da parte de Deus nosso Pai, e da do Senhor Jesus Cristo.';
v[3]  =  'Sempre devemos, irmãos, dar graças a Deus por vós, como é justo, porque a vossa fé cresce muitíssimo e o amor de cada um de vós aumenta de uns para com os outros,';
v[4]  =  'De maneira que nós mesmos nos gloriamos de vós nas igrejas de Deus por causa da vossa paciência e fé, e em todas as vossas perseguições e aflições que suportais;';
v[5]  =  'Prova clara do justo juízo de Deus, para que sejais havidos por dignos do reino de Deus, pelo qual também padeceis;';
v[6]  =  'Se de fato é justo diante de Deus que dê em paga tribulação aos que vos atribulam,';
v[7]  =  'E a vós, que sois atribulados, descanso conosco, quando se manifestar o Senhor Jesus desde o céu com os anjos do seu poder,';
v[8]  =  'Como labareda de fogo, tomando vingança dos que não conhecem a Deus e dos que não obedecem ao evangelho de nosso Senhor Jesus Cristo;';
v[9]  =  'Os quais, por castigo, padecerão eterna perdição, ante a face do Senhor e a glória do seu poder,';
v[10]  =  'Quando vier para ser glorificado nos seus santos, e para se fazer admirável naquele dia em todos os que crêem (porquanto o nosso testemunho foi crido entre vós).';
v[11]  =  'Por isso também rogamos sempre por vós, para que o nosso Deus vos faça dignos da sua vocação, e cumpra todo o desejo da sua bondade, e a obra da fé com poder;';
v[12]  =  'Para que o nome de nosso SENHOR Jesus Cristo seja em vós glorificado, e vós nele, segundo a graça de nosso Deus e do Senhor Jesus Cristo.';
salvaCapitulo(1, v);
v[1]  =  'ORA, irmãos, rogamo-vos, pela vinda de nosso Senhor Jesus Cristo, e pela nossa reunião com ele,';
v[2]  =  'Que não vos movais facilmente do vosso entendimento, nem vos perturbeis, quer por espírito, quer por palavra, quer por epístola, como de nós, como se o dia de Cristo estivesse já perto.';
v[3]  =  'Ninguém de maneira alguma vos engane; porque não será assim sem que antes venha a apostasia, e se manifeste o homem do pecado, o filho da perdição,';
v[4]  =  'O qual se opõe, e se levanta contra tudo o que se chama Deus, ou se adora; de sorte que se assentará, como Deus, no templo de Deus, querendo parecer Deus.';
v[5]  =  'Não vos lembrais de que estas coisas vos dizia quando ainda estava convosco?';
v[6]  =  'E agora vós sabeis o que o detém, para que a seu próprio tempo seja manifestado.';
v[7]  =  'Porque já o mistério da injustiça opera; somente há um que agora resiste até que do meio seja tirado;';
v[8]  =  'E então será revelado o iníquo, a quem o Senhor desfará pelo assopro da sua boca, e aniquilará pelo esplendor da sua vinda;';
v[9]  =  'A esse cuja vinda é segundo a eficácia de Satanás, com todo o poder, e sinais e prodígios de mentira,';
v[10]  =  'E com todo o engano da injustiça para os que perecem, porque não receberam o amor da verdade para se salvarem.';
v[11]  =  'E por isso Deus lhes enviará a operação do erro, para que creiam a mentira;';
v[12]  =  'Para que sejam julgados todos os que não creram a verdade, antes tiveram prazer na iniqüidade.';
v[13]  =  'Mas devemos sempre dar graças a Deus por vós, irmãos amados do SENHOR, por vos ter Deus elegido desde o princípio para a salvação, em santificação do Espírito, e fé da verdade;';
v[14]  =  'Para o que pelo nosso evangelho vos chamou, para alcançardes a glória de nosso SENHOR Jesus Cristo.';
v[15]  =  'Então, irmãos, estai firmes e retende as tradições que vos foram ensinadas, seja por palavra, seja por epístola nossa.';
v[16]  =  'E o próprio nosso Senhor Jesus Cristo e nosso Deus e Pai, que nos amou, e em graça nos deu uma eterna consolação e boa esperança,';
v[17]  =  'Console os vossos corações, e vos confirme em toda a boa palavra e obra.';
salvaCapitulo(2, v);
v[1]  =  'NO demais, irmãos, rogai por nós, para que a palavra do Senhor tenha livre curso e seja glorificada, como também o é entre vós;';
v[2]  =  'E para que sejamos livres de homens dissolutos e maus; porque a fé não é de todos.';
v[3]  =  'Mas fiel é o SENHOR, que vos confirmará, e guardará do maligno.';
v[4]  =  'E confiamos quanto a vós no Senhor, que não só fazeis como fareis o que vos mandamos.';
v[5]  =  'Ora o Senhor encaminhe os vossos corações no amor de Deus, e na paciência de Cristo.';
v[6]  =  'Mandamo-vos, porém, irmãos, em nome de nosso Senhor Jesus Cristo, que vos aparteis de todo o irmão que anda desordenadamente, e não segundo a tradição que de nós recebeu.';
v[7]  =  'Porque vós mesmos sabeis como convém imitar-nos, pois que não nos houvemos desordenadamente entre vós,';
v[8]  =  'Nem de graça comemos o pão de homem algum, mas com trabalho e fadiga, trabalhando noite e dia, para não sermos pesados a nenhum de vós.';
v[9]  =  'Não porque não tivéssemos autoridade, mas para vos dar em nós mesmos exemplo, para nos imitardes.';
v[10]  =  'Porque, quando ainda estávamos convosco, vos mandamos isto, que, se alguém não quiser trabalhar, não coma também.';
v[11]  =  'Porquanto ouvimos que alguns entre vós andam desordenadamente, não trabalhando, antes fazendo coisas vãs.';
v[12]  =  'A esses tais, porém, mandamos, e exortamos por nosso Senhor Jesus Cristo, que, trabalhando com sossego, comam o seu próprio pão.';
v[13]  =  'E vós, irmãos, não vos canseis de fazer o bem.';
v[14]  =  'Mas, se alguém não obedecer à nossa palavra por esta carta, notai o tal, e não vos mistureis com ele, para que se envergonhe.';
v[15]  =  'Todavia não o tenhais como inimigo, mas admoestai-o como irmão.';
v[16]  =  'Ora, o mesmo SENHOR da paz vos dê sempre paz de toda a maneira. O Senhor seja com todos vós.';
v[17]  =  'Saudação da minha própria mão, de mim, Paulo, que é o sinal em todas as epístolas; assim escrevo.';
v[18]  =  'A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém.';
salvaCapitulo(3, v);
	
	iiTessalonicenses = c;
