	var naum;
	var c  = [];
	var v = [];
	
	function salvaCapitulo(i,v1){
		c[i] = v1;
		v = [];
	}
	
v[1]  =  'PESO de Nínive. Livro da visão de Naum, o elcosita.';
v[2]  =  'O SENHOR é Deus zeloso e vingador; o SENHOR é vingador e cheio de furor; o SENHOR toma vingança contra os seus adversários, e guarda a ira contra os seus inimigos.';
v[3]  =  'O SENHOR é tardio em irar-se, mas grande em poder, e ao culpado não tem por inocente; o SENHOR tem o seu caminho na tormenta e na tempestade, e as nuvens são o pó dos seus pés.';
v[4]  =  'Ele repreende ao mar, e o faz secar, e esgota todos os rios; desfalecem Basã e o Carmelo, e a flor do Líbano murcha.';
v[5]  =  'Os montes tremem perante ele, e os outeiros se derretem; e a terra se levanta na sua presença; e o mundo, e todos os que nele habitam.';
v[6]  =  'Quem parará diante do seu furor, e quem persistirá diante do ardor da sua ira? A sua cólera se derramou como um fogo, e as rochas foram por ele derrubadas.';
v[7]  =  'O SENHOR é bom, ele serve de fortaleza no dia da angústia, e conhece os que confiam nele.';
v[8]  =  'E com uma inundação transbordante acabará de uma vez com o seu lugar; e as trevas perseguirão os seus inimigos.';
v[9]  =  'Que pensais vós contra o SENHOR? Ele mesmo vos consumirá de todo; não se levantará por duas vezes a angústia.';
v[10]  =  'Porque ainda que eles se entrelacem como os espinhos, e se saturem de vinho como bêbados, serão inteiramente consumidos como palha seca.';
v[11]  =  'De ti saiu um que maquinou o mal contra o SENHOR, um conselheiro vil.';
v[12]  =  'Assim diz o SENHOR: Por mais seguros que estejam, e por mais numerosos que sejam, ainda assim serão exterminados, e ele passará; eu te afligi, mas não te afligirei mais.';
v[13]  =  'Mas agora quebrarei o seu jugo de sobre ti, e romperei os teus laços.';
v[14]  =  'Contra ti, porém, o SENHOR deu ordem que não haja mais linhagem do teu nome; da casa dos teus deuses exterminarei as imagens de escultura e de fundição; ali farei o teu sepulcro, porque és vil.';
v[15]  =  'Eis sobre os montes os pés do que traz as boas novas, do que anuncia a paz! Celebra as tuas festas, ó Judá, cumpre os teus votos, porque o ímpio não tornará mais a passar por ti; ele é inteiramente exterminado.';
salvaCapitulo(1, v);
v[1]  =  'O DESTRUIDOR subiu contra ti. Guarda tu a fortaleza, vigia o caminho, fortalece os lombos, reforça muito o seu poder.';
v[2]  =  'Porque o SENHOR restaurará a excelência de Jacó como a excelência de Israel; porque os saqueadores os despojaram, e destruíram os seus sarmentos.';
v[3]  =  'Os escudos dos seus fortes serão vermelhos, os homens valorosos estarão vestidos de escarlate, os carros como tochas flamejantes no dia da sua preparação, e os ciprestes serão terrivelmente abalados.';
v[4]  =  'Os carros correrão furiosamente nas ruas, colidirão um contra o outro nos largos caminhos; o seu aspecto será como o de tochas, correrão como relâmpagos.';
v[5]  =  'Ele se lembrará dos seus valentes; eles, porém, tropeçarão na sua marcha; apressar-se-ão para chegar ao seu muro, quando o amparo for preparado.';
v[6]  =  'As portas dos rios se abrirão, e o palácio será dissolvido.';
v[7]  =  'É decretado: ela será levada cativa, conduzida para cima; e as suas servas a acompanharão, gemendo como pombas, batendo em seus peitos.';
v[8]  =  'Nínive desde que existiu tem sido como um tanque de águas, porém elas agora vazam. Parai, parai, clamar-se-á; mas ninguém olhará para trás.';
v[9]  =  'Saqueai a prata, saqueai o ouro, porque não têm fim as provisões, riquezas há de todo o gênero de bens desejáveis.';
v[10]  =  'Vazia, esgotada e devastada está; derrete-se o seu coração, e tremem os joelhos, e em todos os lombos há dor, e os rostos de todos eles enegrecem.';
v[11]  =  'Onde está agora o covil dos leões, e as pastagens dos leõezinhos, onde passeava o leão velho, e o filhote do leão, sem haver ninguém que os espantasse?';
v[12]  =  'O leão arrebatava o que bastava para os seus filhotes, e estrangulava a presa para as suas leoas, e enchia de presas as suas cavernas, e os seus covis de rapina.';
v[13]  =  'Eis que eu estou contra ti, diz o SENHOR dos Exércitos, e queimarei na fumaça os teus carros, e a espada devorará os teus leõezinhos, e arrancarei da terra a tua presa, e não se ouvirá mais a voz dos teus mensageiros.';
salvaCapitulo(2, v);
v[1]  =  'AI da cidade ensangüentada! Ela está toda cheia de mentiras e de rapina; não se aparta dela o roubo.';
v[2]  =  'Estrépito de açoite há, e o barulho do ruído das rodas; e os cavalos atropelam, e carros vão saltando.';
v[3]  =  'O cavaleiro levanta a espada flamejante, como a lança relampejante, e ali haverá uma multidão de mortos, e abundância de cadáveres, e não terão fim os defuntos; tropeçarão nos seus corpos;';
v[4]  =  'Por causa da multidão dos pecados da meretriz mui graciosa, da mestra das feitiçarias, que vendeu as nações com as suas fornicações, e as famílias pelas suas feitiçarias.';
v[5]  =  'Eis que eu estou contra ti, diz o SENHOR dos Exércitos; e levantarei a tua saia sobre a tua face, e às nações mostrarei a tua nudez, e aos reinos a tua vergonha.';
v[6]  =  'E lançarei sobre ti coisas abomináveis, e envergonhar-te-ei, e pôr-te-ei como espetáculo.';
v[7]  =  'E há de ser que, todos os que te virem, fugirão de ti, e dirão: Nínive está destruída, quem terá compaixão dela? Donde te buscarei consoladores?';
v[8]  =  'És tu melhor do que Nô-Amom, que está assentada entre os canais do Nilo, cercada de águas, tendo por esplanada o mar, e ainda o mar por muralha?';
v[9]  =  'Etiópia e Egito eram a sua força, e não tinha fim; Pute e Líbia foram o seu socorro.';
v[10]  =  'Todavia foi levada cativa para o desterro; também os seus filhos foram despedaçados nas entradas de todas as ruas, e sobre os seus nobres lançaram sortes, e todos os seus grandes foram presos com grilhões.';
v[11]  =  'Tu também serás embriagada, e te esconderás; também buscarás força por causa do inimigo.';
v[12]  =  'Todas as tuas fortalezas serão como figueiras com figos temporãos; se os sacodem, caem na boca do que os há de comer.';
v[13]  =  'Eis que o teu povo no meio de ti são como mulheres; as portas da tua terra estarão de todo abertas aos teus inimigos; o fogo consumirá os teus ferrolhos.';
v[14]  =  'Tira águas para o cerco, reforça as tuas fortalezas; entra no lodo, e pisa o barro, pega a forma para os tijolos.';
v[15]  =  'O fogo ali te consumirá, a espada te exterminará; consumir-te-á, como a locusta. Multiplica-te como a locusta, multiplica-te como os gafanhotos.';
v[16]  =  'Multiplicaste os teus negociantes mais do que as estrelas do céu; a locusta se espalhará e voará.';
v[17]  =  'Os teus príncipes são como os gafanhotos, e os teus capitães como os gafanhotos grandes, que se acampam nas sebes nos dias de frio; em subindo o sol voam, de sorte que não se sabe mais o lugar onde estão.';
v[18]  =  'Os teus pastores dormirão, ó rei da Assíria, os teus ilustres repousarão, o teu povo se espalhará pelos montes, sem que haja quem o ajunte.';
v[19]  =  'Não há cura para a tua ferida, a tua chaga é dolorosa. Todos os que ouvirem a tua fama baterão as palmas sobre ti; porque, sobre quem não passou continuamente a tua malícia?';
salvaCapitulo(3, v);
	
	naum = c;